# Generated by Django 6.0.2 on 2026-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=16)),
                ('date_of_birth', models.DateField()),
                ('date_and_time_of_admission', models.DateTimeField()),
                ('medical_history', models.TextField()),
            ],
        ),
    ]
